export enum FighterStateName {
  Idle = 'idle',
  WalkForward = 'walkForward',
  WalkBack = 'walkBack',
  Crouch = 'crouch',
  JumpStart = 'jumpStart',
  JumpAir = 'jumpAir',
  Land = 'land',
  AttackLP        = 'attackLP',
  AttackCrouchLP  = 'attackCrouchLP',
  AttackStandHP   = 'attackStandHP',
  AttackJumpLP    = 'attackJumpLP',
  AttackHadouken  = 'attackHadouken',
  AttackShoryuken = 'attackShoryuken',
  AttackThrow      = 'attackThrow',
  DashForward      = 'dashForward',
  DashBack         = 'dashBack',
  HitStun          = 'hitstun',
  BlockStun        = 'blockstun',
  KnockdownFall    = 'knockdownFall',
  KnockdownGround  = 'knockdownGround',
  WakeUp           = 'wakeUp',           // invincible rising frames after knockdown
}